import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Slider } from '@/components/slider'
import Header from '@/components/header'
import Navigation from '@/components/nav'
import Slideshow from '@/components/slideshow'
import "../styles/Slideshow.module.css";
import HeroContent from '@/components/hero'
import FeatureContent from '@/components/features'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <HeroContent />
        <FeatureContent/>
      </main>
      <footer>C</footer>
    </>
  )
}
