import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Slider } from '@/components/slider'
import Header from '@/components/header'
import Navigation from '@/components/nav'
import Slideshow from '@/components/slideshow'
import "../styles/Slideshow.module.css";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <Slider/>
        <div className="grid grid-cols-4">
          <div className="col-span-1 bg-gray-100">1</div>
          <div className="col-span-2 bg-red-100">
            <Navigation/>
          </div>
          <div className="col-span-1 bg-orange-100">3</div>
        </div>
      </main>
      <footer>C</footer>
    </>
  )
}
